### ISSUE TITLE
[Tinker's JEI] Not working; error log included

### ISSUE THREAD

**Issue by cosmicdan** [PssbleTrngle/MiscIssues#4]
Looks like it's not using obfuscated names for some reason, maybe. Uploaded wrong version perhaps?

Or maybe I have a too-new Forge version. I'm running 1.12.2-14.23.5.2835.

I'd offer more help or even fix it myself, except I can't find your source (even though it's MIT licensed...?)

````
[03:24:59] [Client thread/ERROR] [jei]: Found a broken recipe: com.possibletriangle.tinkersjei.StatsWrapper@204336bb
Failed to get ingredients from recipe wrapper

java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.isEmpty()Z
	at com.possibletriangle.tinkersjei.StatsWrapper.getRepresantives(StatsWrapper.java:63) ~[StatsWrapper.class:?]
	at com.possibletriangle.tinkersjei.StatsWrapper.getIngredients(StatsWrapper.java:44) ~[StatsWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistry.getIngredients(RecipeRegistry.java:286) ~[RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:272) ~[RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:260) [RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:232) [RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.addRecipes(RecipeRegistry.java:169) [RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.<init>(RecipeRegistry.java:98) [RecipeRegistry.class:?]
	at mezz.jei.startup.ModRegistry.createRecipeRegistry(ModRegistry.java:335) [ModRegistry.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:77) [JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
````

**Comment by cosmicdan** [comment]
Sorry, didn't notice that this was a catch-all issue tracker. Title updated.

**Comment by PssbleTrngle** [comment]
That seems weird, will look into it.

**Comment by PssbleTrngle** [comment]
About the source, I will create it's own git repository. This was only a temporary solution

**Comment by LlubNek** [comment]
I'm getting the same thing.  Doesn't crash, doesn't seem to be completely frozen, but it takes hours (at least) for minecraft to start up and this same error message keeps popping up in the log over and over again.

I'm thinking this might be related to another mod I added recently, but I'm still trying to narrow it down.

[latest.log](https://github.com/PssbleTrngle/MiscIssues/files/3095233/latest.log)

**Comment by PssbleTrngle** [comment]
Yes, something seemed to gone wrong in the building process, I uploaded an update working on the latest forge version
